Repository cse110-sp24-group1/cse110-sp24-group1, pull requests merged in 2024-05, with the labels that each got.

#41 system-diagram
  specs/brainstorm/system-diagram.drawio.png
Labels: documentation

#45 added linters within package
  .github/workflows/Linting.yml
  .stylelintrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/home.html
Labels: enhancement

#60 Config Changes for Actions/Local
  .eslintrc.json
  .github/workflows/Linting.yml
  .stylelintrc.json
  eslint.config.js
  eslint.config.mjs
  package.json
  src/styles/tasks.css
Labels: testing

#59 Gwen/Jeff Home Page Frontend
  src/index.html
  src/styles/home.css
Labels: core feature, frontend

#58 Katie/moss newnote and editnode frontend
  src/index.html
  src/scripts/home.js
  src/styles/home.css
  src/styles/tasks.css
  src/test.js
Labels: core feature, frontend

#66 Create style-guidelines.md
  admin/style-guidelines.md
Labels: style, frontend

#88 Favicon and Added Icons
  icons/text-dark.png
  icons/text-hover-dark.png
  icons/text-hover-light.png
  icons/text-light.png
  src/assets/filler.txt
  src/assets/icons/TeamLogo.ico
  src/assets/icons/home-dark.png
  src/assets/icons/home-hover-dark.png
  src/assets/icons/home-hover-light.png
  src/assets/icons/home-light.png
  src/assets/icons/image-dark.png
  src/assets/icons/image-hover-dark.png
  src/assets/icons/image-hover-light.png
  src/assets/icons/image-light.png
  src/assets/icons/markdown-dark.png
  src/assets/icons/markdown-hover-dark.png
  src/assets/icons/markdown-hover-light.png
  src/assets/icons/markdown-light.png
  src/assets/icons/newfolder-dark.png
  src/assets/icons/newfolder-hover-dark.png
  src/assets/icons/newfolder-hover-light.png
  src/assets/icons/newfolder-light.png
  src/assets/icons/newnote-dark.png
  src/assets/icons/newnote-hover-dark.png
  src/assets/icons/newnote-hover-light.png
  src/assets/icons/newnote-light.png
  src/assets/icons/tasklist-dark.png
  src/assets/icons/tasklist-hover-dark.png
  src/assets/icons/tasklist-hover-light.png
  src/assets/icons/tasklist-light.png
  src/assets/icons/text-dark.png
  src/assets/icons/text-hover-dark.png
  src/assets/icons/text-hover-light.png
  src/assets/icons/text-light.png
  src/index.html
  src/scripts/home.js
  src/styles/home.css
  src/styles/vars.css
  src/tasks.html
Labels: frontend

#91 Katie/gwen frontend mobile display
  src/scripts/tasks.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
Labels: frontend

#109 Task List Updates and Delete Functions
  src/scripts/data-storage.js
  src/scripts/tasks.js
Labels: core feature, backend
