Repository cse110-sp24-group1/cse110-sp24-group1, pull requests merged in 2024-06, with the labels that each got.

#120 PurichV/Anshi - add icons/add folder/change colors/add blur
  admin/guidelines/code-style.md
  admin/guidelines/style-guidelines.md
  admin/guidelines/version-control.md
  admin/tasks/task-iteration-1.md
  admin/tasks/task-iteration-2.md
  admin/tasks/task-iteration-3.md
  package-lock.json
  package.json
  specs/adrs/051924-markdown-api.md
  specs/adrs/053124-markdown-apiV2.md
  specs/adrs/053124-remove-buttons.md
  specs/adrs/adr-template.md
  src/index.html
  src/scripts/home.js
  src/scripts/simplemde.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
  src/styles/vars.css
  src/tasks.html
Labels: documentation, enhancement, core feature, style, frontend, design

#123 Katie/Gwen UI Fixes, Buttons, Deleting, etc.
  src/scripts/home.js
  src/scripts/tasks.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
Labels: frontend

#124 Adding font to webpage and create font guideline
  admin/font-guideline.md
  src/index.html
  src/scripts/home.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
  src/tasks.html
Labels: frontend

#126 Folder Icon Added,Delete Folder
  src/scripts/home.js
  src/styles/home.css
Labels: core feature, style, frontend

#131 Delete notes/folders, mobile display, UI issues
  src/index.html
  src/scripts/data-storage.js
  src/scripts/home.js
  src/scripts/tasks.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
  src/tasks.html
Labels: frontend

#130 Testing task list
  src/scripts/tasks.js
  src/tests/tasks.test.js
Labels: testing

#134 Purich v/anshi fix md image
  src/index.html
  src/scripts/home.js
  src/scripts/tasks.js
Labels: bug, core feature, frontend

#137 Backend
  package-lock.json
  package.json
  src/scripts/data-storage.js
  src/scripts/tasks.js
  src/tasks.html
  src/test-until-pages.html
  src/tests/data-schema.test.js
  src/tests/tasks.test.js
Labels: testing, backend

#138 JSDocs Test
  .github/workflows/jsDocs.yml
  docs/HomeScript.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/scripts/data-storage.js
Labels: documentation

#139 Added search, edit, delete, back icons & nothing here diagram
  admin/meetings/meeting-files/052624-retrospective6.png
  src/assets/icons/back-dark.png
  src/assets/icons/back-hover-dark.png
  src/assets/icons/back-hover-light.png
  src/assets/icons/back-light.png
  src/assets/icons/delete-dark.png
  src/assets/icons/delete-hover-dark.png
  src/assets/icons/delete-hover-light.png
  src/assets/icons/delete-light.png
  src/assets/icons/edit-dark.png
  src/assets/icons/edit-hover-dark.png
  src/assets/icons/edit-hover-light.png
  src/assets/icons/edit-light.png
  src/assets/icons/emptyFolder.png
  src/assets/icons/search-dark.png
  src/assets/icons/search-hover-dark.png
  src/assets/icons/search-hover-light.png
  src/assets/icons/search-light.png
Labels: design

#143 Add tests for delete functions to data-schema.test.js
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/tests/data-schema.test.js
Labels: testing

#149 Folder tests
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/tests/folders.test.js
Labels: testing

#146 Testing Journal Entries
  src/tests/notes.test.js
Labels: testing

#147 Added Icons for Back, Added Center Diagram Placeholder
  src/index.html
  src/scripts/home.js
  src/styles/home.css
Labels: frontend

#151 Small changes for the delete confirmation modal and create new folder button
  docs/home.js.html
  docs/index.html
  src/index.html
  src/scripts/home.js
  src/styles/home.css
Labels: style, frontend, design

#159 Automated Unit Tests for Jest
  .github/workflows/unit-tests.yml
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  package.json
  src/tests/data-schema.test.js
  src/tests/folders.test.js
  src/tests/notes.test.js
  src/tests/tasks.test.js
Labels: testing, backend

#161 Fixed the no script tags
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/index.html
  src/tasks.html
Labels: design

#165 Nothing here svgs updates
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/scripts/home.js
  src/scripts/tasks.js
  src/styles/home.css
  src/styles/tasks.css
Labels: frontend

#166 Fixed the white flickering that happened every refresh
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/index.html
  src/scripts/global.js
  src/scripts/tasks.js
  src/styles/global.css
  src/styles/home.css
  src/styles/tasks.css
  src/tasks.html
Labels: enhancement

#171 fix the flicker
  docs/HomeScript.html
  docs/TaskList.html
  docs/data-storage.js.html
  docs/global.html
  docs/global.js.html
  docs/home.js.html
  docs/index.html
  docs/tasks.js.html
  src/index.html
  src/tasks.html
Labels: bug
